### ISSUE TITLE
Allow passing parameters in query string

### ISSUE THREAD

**Issue by drasko** [mainflux/mainflux-cli#1]
Needed for https://github.com/mainflux/mainflux/issues/73 and others

**Comment by drasko** [comment]
@manuIO what's the status on this?

**Comment by manuIO** [comment]
@drasko I'm on it. I'll try to push something tomorrow or this night!

**Comment by manuIO** [comment]
can be closed: https://github.com/mainflux/mainflux-cli/pull/9

**Comment by drasko** [comment]
Cool. Can you just tell me how these flags are documented? I.e. - how user can see that they exist?

**Comment by manuIO** [comment]
@drasko I need to improve documentation inside CLI. For the moment the user can see how it works with the command: `mainflux-cli msg get --help`

**Comment by drasko** [comment]
Are the `start_time` and `end_time` flags mentioned when `mainflux-cli msg get --help` is executed?

**Comment by manuIO** [comment]
yes

**Comment by drasko** [comment]
Can this one be closed?

**Comment by manuIO** [comment]
@drasko yes!
