### ISSUE TITLE
Add support for Auth

### ISSUE THREAD

**Issue by drasko** [mainflux/mainflux-cli#2]
New commands should be added to support Mainflux Auth, like API Key provisioning and similar.  Basically - what has been described [here](http://mainflux.io/security) - turn these `curls` into CLI commands.

**Comment by drasko** [comment]
Is this one fixed, can it be closed?

**Comment by manuIO** [comment]
@drasko I'm on it. For the moment only create user and create session is finished. I'll try to push tomorrow!

**Comment by manuIO** [comment]
@drasko I've added some auth commands here:
https://github.com/mainflux/mainflux-cli/pull/8/commits/7b1f3370ad4badf2a7e4254ca765a036dd1477bb

Need help for delete and update commands.

**Comment by drasko** [comment]
I would close this one for now, until we figure out how Auth will really work. Then we will reopen new one that task, that will be better defined.
