### ISSUE TITLE
Go with non-interactive CLI - switch to Cobra

### ISSUE THREAD

**Issue by drasko** [mainflux/mainflux-cli#3]
After some experiencs with ishell, I think we should switch to Cobra: https://github.com/spf13/cobra and use non-interactive CLI for now - until cobra implements eventually something interactive.

I see Mainflux CLI something similar to Docker CLI.

We'll need optinons (flags), subcommands and whatnot - ishell can not support these. As CLI complicates (query parameters, auth support, ...) we will need robust library. Cobra is robust and battle-proven, used by Kubernetes, ProjectAtomic and similar.

**Comment by manuIO** [comment]
Ok

**Comment by drasko** [comment]
Closing this one - cool job @manuIO!
